---
className: "CrossLanguageTransform"
classPath: "sampletransform.CrossLanguageTransform"
constructorName: "sampletransform.CrossLanguageTransform"
isConstructorStatic: false
constructorArgs:
- type: "sampletransform.CrossLanguageTransform$LengthConfig"
  argumentName: "lengthConfig"
  renderAs: null
configurers:
- configurerName: "withOtherConfig"
  arguments:
  - type: "sampletransform.CrossLanguageTransform$OtherConfig"
    argumentName: "otherConfig"
    renderAs: null
flattenedConfigurerArgs: null
types:
  sampletransform.CrossLanguageTransform$OtherConfig:
  - name: "k"
    type: "int"
    renderAs: null
  - name: "nestedConfig"
    type: "sampletransform.CrossLanguageTransform$NestedConfig"
    renderAs: null
  sampletransform.CrossLanguageTransform$NestedConfig:
  - name: "string"
    type: "java.lang.String"
    renderAs: null
  sampletransform.CrossLanguageTransform$LengthConfig:
  - name: "maxLength"
    type: "int"
    renderAs: null
  - name: "minLength"
    type: "int"
    renderAs: null
constructorStatic: false
